# Generated by Django 5.0.3 on 2024-03-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
