# Generated by Django 5.0.3 on 2024-03-23 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_color_color_remove_color_product_and_more'),
        ('wishlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wishlist_pro',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlists_pro', to='products.product'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wishlist_user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
