# Generated by Django 5.0.3 on 2024-03-25 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_color_color_remove_color_product_and_more'),
        ('wishlist', '0002_remove_wishlist_product_id_remove_wishlist_user_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists_pro', to='products.product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
