# Generated by Django 5.0.3 on 2024-03-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
