# Generated by Django 5.0.3 on 2024-03-16 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('apartment', models.CharField(max_length=100)),
                ('town_city', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cupon_code', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[('K', 'Karta'), ('N', 'Naxt')], max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Checkout', to='account.user')),
                ('basket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Checkout', to='basket.basket')),
                ('billing_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Checkout', to='checkout.billingdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
