# Generated by Django 5.0.3 on 2024-03-28 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('products', '0007_rename_name_color_color_rename_name_size_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cupon_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_checkout', models.BooleanField(default=False)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('card_date', models.CharField(blank=True, max_length=5, null=True)),
                ('payment_type', models.CharField(choices=[('K', 'Karta'), ('N', 'Naxt')], max_length=1)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('total_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CheckoutProduct', to=settings.AUTH_USER_MODEL)),
                ('billing_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Checkoutbilling', to='checkout.billingdetails')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.size')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CheckoutProduct',
        ),
    ]
