# Generated by Django 5.0.3 on 2024-03-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='card_date',
            field=models.CharField(blank=True, default='01/23', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='card_number',
            field=models.CharField(blank=True, default='9860 0000 1111 2222', max_length=20, null=True),
        ),
    ]
