# Generated by Django 5.0.3 on 2024-03-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_productcheckout_delete_checkoutproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcheckout',
            name='test',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
