# Generated by Django 5.0.3 on 2024-03-26 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_remove_basket_product_basket'),
        ('checkout', '0002_checkout_card_date_checkout_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='basket_id',
        ),
        migrations.AddField(
            model_name='checkout',
            name='product_basket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_basket', to='basket.productbasket'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='card_date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
