# Generated by Django 5.0.3 on 2024-03-28 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_remove_basket_product_basket'),
        ('checkout', '0002_checkoutproduct_product_alter_checkoutbasket_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutproduct',
            name='product',
        ),
        migrations.AlterField(
            model_name='checkoutbasket',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CheckoutBasket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkoutbasket',
            name='billing_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CheckoutBasket', to='checkout.billingdetails'),
        ),
        migrations.AlterField(
            model_name='checkoutbasket',
            name='product_basket',
            field=models.ManyToManyField(related_name='product_basket', to='basket.productbasket'),
        ),
        migrations.AlterField(
            model_name='checkoutproduct',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CheckoutProduct', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkoutproduct',
            name='billing_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CheckoutProduct', to='checkout.billingdetails'),
        ),
    ]
