# Generated by Django 5.0.3 on 2024-03-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_remove_basket_product_basket'),
        ('checkout', '0003_remove_checkout_basket_id_checkout_product_basket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_checkout',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='product_basket',
        ),
        migrations.AddField(
            model_name='checkout',
            name='product_basket',
            field=models.ManyToManyField(related_name='product_basket', to='basket.productbasket'),
        ),
    ]
