# Generated by Django 5.0.3 on 2024-03-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_checkoutproduct_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='checkoutproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='checkoutproduct',
            name='size',
        ),
    ]
