# Generated by Django 5.0.3 on 2024-03-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_productcheckout_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcheckout',
            name='test',
        ),
    ]
