# Generated by Django 5.0.3 on 2024-03-28 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_productcheckout_test'),
        ('products', '0007_rename_name_color_color_rename_name_size_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcheckout',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product_checkout', to='products.product'),
            preserve_default=False,
        ),
    ]
