# Generated by Django 5.0.3 on 2024-03-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_checkout_is_checkout_remove_checkout_product_basket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='cupon_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
