# Generated by Django 5.0.3 on 2024-03-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_remove_basket_product_basket'),
        ('checkout', '0005_alter_checkout_cupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='product_basket',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_basket', to='basket.productbasket'),
        ),
    ]
