# Generated by Django 5.0.3 on 2024-03-27 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_remove_basket_product_basket'),
        ('checkout', '0006_alter_checkout_product_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='product_basket',
        ),
        migrations.CreateModel(
            name='CheckoutProduct',
            fields=[
                ('checkout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkout.checkout')),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('total_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('checkout.checkout',),
        ),
        migrations.CreateModel(
            name='CheckoutBasket',
            fields=[
                ('checkout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkout.checkout')),
                ('product_basket', models.ManyToManyField(related_name='product_basket', to='basket.productbasket')),
            ],
            options={
                'abstract': False,
            },
            bases=('checkout.checkout',),
        ),
    ]
