# Generated by Django 5.0.3 on 2024-03-27 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_remove_checkout_product_basket_checkoutproduct_and_more'),
        ('products', '0002_remove_color_color_remove_color_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutproduct',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color'),
        ),
        migrations.AlterField(
            model_name='checkoutproduct',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size'),
        ),
    ]
