# Generated by Django 5.0.3 on 2024-03-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='image',
            field=models.ImageField(blank=True, upload_to='workers/images'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='instagram',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='workers',
            name='linkedin',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='workers',
            name='twitter',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
