# Generated by Django 5.0.3 on 2024-03-26 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basket', '0007_remove_basket_product_basket'),
        ('checkout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payemnt_type', models.CharField(choices=[('K', 'Karta'), ('N', 'Naxt')], max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to=settings.AUTH_USER_MODEL)),
                ('basket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='basket.basket')),
                ('billing_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='checkout.billingdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
