# Generated by Django 5.0.3 on 2024-03-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_basket_user_productbasket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbasket',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
