# Generated by Django 5.0.3 on 2024-03-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_alter_productbasket_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product_basket',
        ),
    ]
