# Generated by Django 5.0.3 on 2024-03-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_remove_basket_product_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='sum',
            field=models.FloatField(default=0.0),
        ),
    ]
