# Generated by Django 5.0.3 on 2024-03-25 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_alter_basket_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='product_basket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_basket', to='basket.productbasket'),
            preserve_default=False,
        ),
    ]
