# Generated by Django 5.0.3 on 2024-03-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_basket_product_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product_basket',
        ),
    ]
