# Generated by Django 5.0.3 on 2024-03-28 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='products.product'),
        ),
        migrations.AlterField(
            model_name='size',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='products.product'),
        ),
        migrations.AlterField(
            model_name='stars',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='products.product'),
        ),
    ]
